const mongoose = require("mongoose");
const db = require("../models");
mongoose.Promise = global.Promise;

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/miridonhunters",
  {
    useMongoClient: true
  }
);

const weaponSeed = [
  { name: "Hand Drill", material: "steel", type: "weapon", subtype: "drill", cost: 2, weight: 2, damage: "1d6", tohit: 0, special: "[ {'Physical Damage Reduction Damage', 0}, {'Mech Physical Damage Reduction Damage', 1} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Arm Drill", material: "steel", type: "weapon", subtype: "drill", cost: 5.6, weight: 5, damage: "2d6", tohit: 1, special: "[ {'Physical Damage Reduction', 1}, {'Mech Physical Damage Reduction Damage', 1} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Power Drill", material: "steel", type: "weapon", subtype: "drill", cost: 11.3, weight: 7, damage: "3d6", tohit: 2, special: "[ {'Physical Damage Reduction', 1}, {'Mech Physical Damage Reduction Damage', 2} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Grand Drill", material: "steel", type: "weapon", subtype: "drill", cost: 32, weight: 10, damage: "4d6", tohit: 3, special: "[ {'Physical Damage Reduction', 1}, {'Mech Physical Damage Reduction Damage', 3} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Star Drill", material: "steel", type: "weapon", subtype: "drill", cost: 181, weight: 15, damage: "6d6", tohit: 4, special: "[ {'Physical Damage Reduction', 2}, {'Mech Physical Damage Reduction Damage', 5} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Heaven Piercing Drill", material: "steel", type: "weapon", subtype: "drill", cost: 1024, weight: 20, damage: "8d6", tohit: 6, special: "[ {'Physical Damage Reduction', 2}, {'Mech Physical Damage Reduction Damage', 7} ]", description: "Drills are designed as an anti-mech unit. Their principal ability purpose is to break the defenses of an opponent. Every time they hit they reduce the physical damage reduction of their opponent for the the rest of the given round by a set amount (Physical Damage Reduction Damage for humans, Mech Physical Damage Reduction Damage for mechs). The physical damage reduction is restored at the beginning of the next round. If the wielder has the special ability of the 'Techie' class 'Mech Training', that skill is also added to the 'Physical Damage Reduction Damage' and twice to the 'Mech Physical Damage Reduction Damage'." },
  { name: "Unarmed", material: "steel", type: "weapon", subtype: "grappling", cost: 0, weight: 0, damage: "1", tohit: 0, special: "[ {'Grapple Attack Bonus', 0}, {'Redouble Bonus', 20}, {'Grapple Speed', 0} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Claw", material: "steel", type: "weapon", subtype: "grappling", cost: 1.4, weight: 1, damage: "1d6-1", tohit: 0, special: "[ {'Grapple Attack Bonus', 1}, {'Redouble Bonus', 10}, {'Grapple Speed', 1} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Clawed Gauntlet", material: "steel", type: "weapon", subtype: "grappling", cost: 2.8, weight: 3, damage: "1d6+1", tohit: 1, special: "[ {'Grapple Attack Bonus', 3}, {'Redouble Bonus', 8}, {'Grapple Speed', 1} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Robot Arm", material: "steel", type: "weapon", subtype: "grappling", cost: 5.6, weight: 5, damage: "2d6-1", tohit: 2, special: "[ {'Grapple Attack Bonus', 4}, {'Redouble Bonus', 6}, {'Grapple Speed', 2} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Dragon Claw", material: "steel", type: "weapon", subtype: "grappling", cost: 16, weight: 8, damage: "2d6+1", tohit: 3, special: "[ {'Grapple Attack Bonus', 5}, {'Redouble Bonus', 3}, {'Grapple Speed', 2} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Mech Arm", material: "steel", type: "weapon", subtype: "grappling", cost: 32, weight: 10, damage: "3d6", tohit: 3, special: "[ {'Grapple Attack Bonus', 6}, {'Redouble Bonus', 1}, {'Grapple Speed', 3} ]", description: "Grappling weapons are fast melee weapon that are worn on both hands (or are both hands). They get a bonus to the grapple attack and redouble skills. The speed points lost by a grappled target are increased when the grappling character is wearing a grappling weapon." },
  { name: "Hand hammer", material: "steel", type: "weapon", subtype: "hammer", cost: 2, weight: 2, damage: "1d6", tohit: 0, special: "[ {'Speed Point Damage', 0} ]", description: "Hammers are a weapon designed to control the battlefield. Hammers reduce a target's speed points for the remaining of the round." },
  { name: "War Hammer", material: "steel", type: "weapon", subtype: "hammer", cost: 8, weight: 6, damage: "3d6", tohit: 1, special: "[ {'Speed Point Damage', 1} ]", description: "Hammers are a weapon designed to control the battlefield. Hammers reduce a target's speed points for the remaining of the round." },
  { name: "Maul", material: "steel", type: "weapon", subtype: "hammer", cost: 32, weight: 10, damage: "5d6", tohit: 2, special: "[ {'Speed Point Damage', 3} ]", description: "Hammers are a weapon designed to control the battlefield. Hammers reduce a target's speed points for the remaining of the round." },
  { name: "Great Maul", material: "steel", type: "weapon", subtype: "hammer", cost: 181, weight: 15, damage: "8d6", tohit: 3, special: "[ {'Speed Point Damage', 4} ]", description: "Hammers are a weapon designed to control the battlefield. Hammers reduce a target's speed points for the remaining of the round." },
  { name: "The Crusher", material: "steel", type: "weapon", subtype: "hammer", cost: 1024, weight: 20, damage: "10d6", tohit: 5, special: "[ {'Speed Point Damage', 5} ]", description: "Hammers are a weapon designed to control the battlefield. Hammers reduce a target's speed points for the remaining of the round." },
  { name: "Palm Pistol", material: "steel", type: "weapon", subtype: "pistol", cost: 2, weight: 2, damage: "1d6", tohit: 0, range: 50, special: "[]", description: "Pistols are the standard guns from Miridon." },
  { name: "Revolver", material: "steel", type: "weapon", subtype: "pistol", cost: 5.6, weight: 5, damage: "2d6-1", tohit: 0, range: 60, special: "[]", description: "Pistols are the standard guns from Miridon." },
  { name: "Heavy Revolver", material: "steel", type: "weapon", subtype: "pistol", cost: 16, weight: 8, damage: "3d6", tohit: -1, range: 70, special: "[]", description: "Pistols are the standard guns from Miridon." },
  { name: "Hand Cannon", material: "steel", type: "weapon", subtype: "pistol", cost: 45.2, weight: 11, damage: "4d6", tohit: -2, range: 80, special: "[]", description: "Pistols are the standard guns from Miridon." },
  { name: "Dreadnaught", material: "steel", type: "weapon", subtype: "pistol", cost: 181, weight: 15, damage: "5d6", tohit: -2, range: 90, special: "[]", description: "Pistols are the standard guns from Miridon." },
  { name: "Small Shield", material: "steel", type: "weapon", subtype: "shield", cost: 2, weight: 2, damage: "0", tohit: 2, special: "[ {'Block Bonus', 1}, {'Heavy Block Bonus', 1}, {'Super Block Bonus', 1} ]", description: "Shields are a basic defensive melee weapon. They are primarily designed to be used as a defensive weapon. When using a [Shield Block] action, the [Block], [Heavy Block], and [Super Block] abilities reduce additional damage. When used offensively, they deal a small amount of damage, but have a very large bonus to hit. " },
  { name: "Large Shield", material: "steel", type: "weapon", subtype: "shield", cost: 4, weight: 4, damage: "1d6-1", tohit: 4, special: "[ {'Block Bonus', 2}, {'Heavy Block Bonus', 4}, {'Super Block Bonus', 6} ]", description: "Shields are a basic defensive melee weapon. They are primarily designed to be used as a defensive weapon. When using a [Shield Block] action, the [Block], [Heavy Block], and [Super Block] abilities reduce additional damage. When used offensively, they deal a small amount of damage, but have a very large bonus to hit. " },
  { name: "Great Shield", material: "steel", type: "weapon", subtype: "shield", cost: 11.3, weight: 7, damage: "1d6+1", tohit: 5, special: "[ {'Block Bonus', 3}, {'Heavy Block Bonus', 5}, {'Super Block Bonus', 7} ]", description: "Shields are a basic defensive melee weapon. They are primarily designed to be used as a defensive weapon. When using a [Shield Block] action, the [Block], [Heavy Block], and [Super Block] abilities reduce additional damage. When used offensively, they deal a small amount of damage, but have a very large bonus to hit. " },
  { name: "Grand Shield", material: "steel", type: "weapon", subtype: "shield", cost: 32, weight: 10, damage: "2d6", tohit: 7, special: "[ {'Block Bonus', 5}, {'Heavy Block Bonus', 8}, {'Super Block Bonus', 10} ]", description: "Shields are a basic defensive melee weapon. They are primarily designed to be used as a defensive weapon. When using a [Shield Block] action, the [Block], [Heavy Block], and [Super Block] abilities reduce additional damage. When used offensively, they deal a small amount of damage, but have a very large bonus to hit. " },
  { name: "Monument Shield", material: "steel", type: "weapon", subtype: "shield", cost: 181, weight: 15, damage: "3d6", tohit: 9, special: "[ {'Block Bonus', 7}, {'Heavy Block Bonus', 10}, {'Super Block Bonus', 15} ]", description: "Shields are a basic defensive melee weapon. They are primarily designed to be used as a defensive weapon. When using a [Shield Block] action, the [Block], [Heavy Block], and [Super Block] abilities reduce additional damage. When used offensively, they deal a small amount of damage, but have a very large bonus to hit. " },
  { name: "Shotgun", material: "steel", type: "weapon", subtype: "shotgun", cost: 5.6, weight: 5, damage: "1d6", tohit: 0, range: 50, special: "[ {'Bullets Fired Per Shot', 6} ]", description: "Shotguns fire several bullets simultaneously. The bullets have a fairly short range. Each shot fires multiple bullets." },
  { name: "Spreadshot", material: "steel", type: "weapon", subtype: "shotgun", cost: 16, weight: 8, damage: "1d6+2", tohit: -1, range: 50, special: "[ {'Bullets Fired Per Shot', 9} ]", description: "Shotguns fire several bullets simultaneously. The bullets have a fairly short range. Each shot fires multiple bullets." },
  { name: "Scattershot", material: "steel", type: "weapon", subtype: "shotgun", cost: 45.2, weight: 11, damage: "2d6", tohit: -1, range: 45, special: "[ {'Bullets Fired Per Shot', 12} ]", description: "Shotguns fire several bullets simultaneously. The bullets have a fairly short range. Each shot fires multiple bullets." },
  { name: "Iron Mist", material: "steel", type: "weapon", subtype: "shotgun", cost: 181, weight: 15, damage: "2d6+2", tohit: -3, range: 40, special: "[ {'Bullets Fired Per Shot', 15} ]", description: "Shotguns fire several bullets simultaneously. The bullets have a fairly short range. Each shot fires multiple bullets." },
  { name: "Bullet Rain Storm", material: "steel", type: "weapon", subtype: "shotgun", cost: 1024, weight: 20, damage: "3d6", tohit: -4, range: 40, special: "[ {'Bullets Fired Per Shot', 20} ]", description: "Shotguns fire several bullets simultaneously. The bullets have a fairly short range. Each shot fires multiple bullets." },
  { name: "Hunting Rifle", material: "steel", type: "weapon", subtype: "sniper rifle", cost: 5.6, weight: 5, damage: "1d6+1", tohit: 0, range: 50, special: "[ {'Steady Shot Bonus', 2} ]", description: "Sniper Rifles are designed for firing at a long range. They have multiple range increments, each with different penalties to accuracy." },
  { name: "Battle Rifle", material: "steel", type: "weapon", subtype: "sniper rifle", cost: 16, weight: 8, damage: "3d6", tohit: -1, range: 55, special: "[ {'Steady Shot Bonus', 3} ]", description: "Sniper Rifles are designed for firing at a long range. They have multiple range increments, each with different penalties to accuracy." },
  { name: "Heavy Rifle", material: "steel", type: "weapon", subtype: "sniper rifle", cost: 64, weight: 12, damage: "4d6", tohit: -2, range: 60, special: "[ {'Steady Shot Bonus', 4} ]", description: "Sniper Rifles are designed for firing at a long range. They have multiple range increments, each with different penalties to accuracy." },
  { name: "Targeting Cannon", material: "steel", type: "weapon", subtype: "sniper rifle", cost: 181, weight: 15, damage: "5d6", tohit: -3, range: 65, special: "[ {'Steady Shot Bonus', 6} ]", description: "Sniper Rifles are designed for firing at a long range. They have multiple range increments, each with different penalties to accuracy." },
  { name: "Hand Howitzer", material: "steel", type: "weapon", subtype: "sniper rifle", cost: 1024, weight: 20, damage: "7d6", tohit: -4, range: 80, special: "[ {'Steady Shot Bonus', 8} ]", description: "Sniper Rifles are designed for firing at a long range. They have multiple range increments, each with different penalties to accuracy." },
  { name: "Longsword", material: "steel", type: "weapon", subtype: "sword", cost: 2, weight: 2, damage: "1d6+1", tohit: 1, special: "[]", description: "Swords are the basic melee weapon. Their bonus to hit allows melee fighters to keep up with speedier characters." },
  { name: "Claymore (sword)", material: "steel", type: "weapon", subtype: "sword", cost: 4, weight: 4, damage: "2d6", tohit: 2, special: "[]", description: "Swords are the basic melee weapon. Their bonus to hit allows melee fighters to keep up with speedier characters." },
  { name: "Greatsword", material: "steel", type: "weapon", subtype: "sword", cost: 11.3, weight: 7, damage: "3d6", tohit: 3, special: "[]", description: "Swords are the basic melee weapon. Their bonus to hit allows melee fighters to keep up with speedier characters." },
  { name: "Grand Saber", material: "steel", type: "weapon", subtype: "sword", cost: 32, weight: 10, damage: "4d6", tohit: 4, special: "[]", description: "Swords are the basic melee weapon. Their bonus to hit allows melee fighters to keep up with speedier characters." },
  { name: "Monument Sword", material: "steel", type: "weapon", subtype: "sword", cost: 181, weight: 15, damage: "6d6", tohit: 6, special: "[]", description: "Swords are the basic melee weapon. Their bonus to hit allows melee fighters to keep up with speedier characters." },
  { name: "Stun Pistol", material: "steel", type: "weapon", subtype: "tesla", cost: 2, weight: 2, damage: "1d6-1", tohit: 0, range: 20, special: "[ {'Strength Point Damage', 2}, {'Speed Point Damage', 1} ]", description: "Teslas fire a charged burst of pure electricity at an opponent. This burst takes away some of a targets speed and strength points." },
  { name: "Shock Gun", material: "steel", type: "weapon", subtype: "tesla", cost: 5.6, weight: 5, damage: "1d6", tohit: 0, range: 20, special: "[ {'Strength Point Damage', 4}, {'Speed Point Damage', 2} ]", description: "Teslas fire a charged burst of pure electricity at an opponent. This burst takes away some of a targets speed and strength points." },
  { name: "Plasma Rifle", material: "steel", type: "weapon", subtype: "tesla", cost: 22.6, weight: 9, damage: "2d6-1", tohit: -1, range: 15, special: "[ {'Strength Point Damage', 6}, {'Speed Point Damage', 3} ]", description: "Teslas fire a charged burst of pure electricity at an opponent. This burst takes away some of a targets speed and strength points." },
  { name: "Battery Arm", material: "steel", type: "weapon", subtype: "tesla", cost: 64, weight: 12, damage: "2d6+1", tohit: -1, range: 15, special: "[ {'Strength Point Damage', 8}, {'Speed Point Damage', 5} ]", description: "Teslas fire a charged burst of pure electricity at an opponent. This burst takes away some of a targets speed and strength points." },
  { name: "Plasma Cannon", material: "steel", type: "weapon", subtype: "tesla", cost: 181, weight: 15, damage: "3d6", tohit: -2, range: 10, special: "[ {'Strength Point Damage', 10}, {'Speed Point Damage', 6} ]", description: "Teslas fire a charged burst of pure electricity at an opponent. This burst takes away some of a targets speed and strength points." }  
];

db.Exchange
  .remove({})
  .then(() => db.Weapon.collection.insertMany(weaonSeed))
  .then(data => {
    console.log(data.insertedIds.length + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
